---

- name: Set ACME account email
  community.openwrt.uci:
    command: set
    key: acme.@acme[0].account_email
    value: "{{ acme_account_email }}"

- name: Configure ACME certificate
  community.openwrt.uci:
    command: section
    config: acme
    type: cert
    name: webui
    value:
      enabled: "1"
      validation_method: dns
      dns: dns_aws
      key_type: "{{ acme_keytype }}"
      update_uhttpd: "1"
      domains: "{{ inventory_hostname }}"
      credentials:
        - "AWS_ACCESS_KEY_ID={{ route53_access_key_id }}"
        - "AWS_SECRET_ACCESS_KEY={{ route53_secret_access_key }}"
  no_log: true

- name: Commit ACME config
  community.openwrt.uci:
    command: commit
    config: acme
  notify: renew acme